# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.255.230:3306/icbc
    username: root
    password: kingvern
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8080

shiro-redis:
  enabled: true
  redis-manager:
    host: 47.95.255.230:6379
icbc:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5

    expire: 604800
    header: Authorization
